# Actions train a model on Azure Machine Learnin g
name: aml-train
on: # [pull_request]
  [push]

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Check Out Repository
      id: checkout_repository
      uses: actions/checkout@v2
        
    # Connect or Create the Azure Machine Learning Workspace
    - name: Connect/Create Azure Machine Learning Workspace
      id: aml_workspace
      uses: Azure/aml-workspace@v1
      with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
    
    # Connect or Create a Compute Target in Azure Machine Learning
    - name: Connect/Create Azure Machine Learning Compute Target
      id: aml_compute_training
      uses: Azure/aml-compute@v1
      with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
    
    # Submit a training run to the Azure Machine Learning
    - name: Submit training run
      id: aml_run
      uses: Azure/aml-run@v1
      with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}

    # Commenting as currently workflow runs on github push, not on a pull request or issue comment
    # Therefore, comment instead on commit
    #- name: comment PR
    #  uses: unsplash/comment-on-pr@master
    #  env:
    #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #  with:
    #    msg: "${{ steps.aml_run.outputs.run_metrics }}"
    
    - name: Create comment on commit
      uses: peter-evans/commit-comment@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        body: ${{ steps.aml_run.outputs.run_metrics }}
    
    # Register model in Azure Machine Learning model registry
    - name: Register model
      id: aml_registermodel
      uses: Azure/aml-registermodel@v1
      with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
          run_id:  ${{ steps.aml_run.outputs.run_id }}
          experiment_name: ${{ steps.aml_run.outputs.experiment_name }}
          
    # Commenting as currently workflow runs on github push, not on a pull request or issue comment
    # Therefore, comment instead on commit
    #- name: comment PR
    #  uses: unsplash/comment-on-pr@master
    #  env:
    #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #  with:
    #    msg: "${{ steps.aml_registermodel.outputs.model_id }}"
    - name: Create comment on commit
      uses: peter-evans/commit-comment@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        body: ${{ steps.aml_registermodel.outputs.model_id }}

    # - uses: actions/upload-artifact@v1
    #   with:
    #     name: ${{ steps.aml_run.outputs.model }}
    #     path: SpatialSimOutputs

